linters:
  enable:
    - gofmt
    - govet
    - ineffassign
    - misspell
    - unconvert
    - gocritic
    - goimports
    - gosec
    - gosimple
    - staticcheck
    - unused
    - errcheck
    - revive

linters-settings:
  gofmt:
    simplify: true
  govet:
    enable-all: true
  revive:
    confidence: 0.8
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
run:
  timeout: 5m
  tests: false