version: "2"

linters:
  enable:
    - govet
    - ineffassign
    - misspell
    - unconvert
    - gocritic
    - gosec
    - gosimple
    - staticcheck
    - unused
    - errcheck
    - revive
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    revive:
      confidence: 0.8
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
  exclusions:
    rules:
      # Exclude some linters from running on test files
      - path: _test\.go
        linters:
          - gosec
      # Ignore hugeParam warnings for receiver methods (Bubble Tea pattern)
      - linters:
          - gocritic
        text: "hugeParam.*is heavy.*consider passing it by pointer"
      # Ignore false positive append warnings
      - linters:
          - gocritic
        text: "appendAssign: append result not assigned to the same slice"
      # Ignore style preferences for if-else chains and single case switches
      - linters:
          - gocritic
        text: "ifElseChain: rewrite if-else to switch statement"
      - linters:
          - gocritic
        text: "singleCaseSwitch: should rewrite switch statement to if statement"
      # Allow subprocess with user input (needed for agent execution)
      - linters:
          - gosec
        text: "G204: Subprocess launched with a potential tainted input"
      # Allow file inclusion (needed for reading user-specified files)
      - linters:
          - gosec
        text: "G304: Potential file inclusion via variable"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  
run:
  timeout: 5m
  tests: false